import React, { useContext } from "react";
import { motion } from "motion/react";
import { Link } from "react-router-dom";
import AuthContext from "../../Context/AuthContext";
import { Sparkles, BookOpen, Coins, ArrowRight, Upload, Star, GraduationCap } from "lucide-react";

export default function Hero() {
  const { userId } = useContext(AuthContext);

  return (
    <div className="page-wrapper">

      {/* ── Hero Main Area ── */}
      <section className="hero-main-section">
        <div className="hero-main-container">
          {/* Left Copy */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
            className="hero-left-content"
          >
            {/* Coral Line Accent */}
            <div className="hero-line-accent" />

            <h1 className="text-display-large hero-title">
              High-quality<br />
              exam solutions,<br />
              <span className="italic-serif hero-title-sub">
                powered by<br />
                the community.
              </span>
            </h1>

            <p className="hero-desc">
              A curated archive of past university exams, complete with detailed, step-by-step answers generated by AI.
            </p>

            <div className="hero-buttons-container">
              <Link
                to={userId ? "/papers" : "/signup"}
                className="btn-filled hero-btn-filled"
              >
                {userId ? "Browse Papers" : "Get Started Free"}
                <ArrowRight size={16} />
              </Link>
              <Link
                to={userId ? "/upload" : "/login"}
                className="btn-outlined hero-btn-outlined"
              >
                {userId ? "Upload Paper" : "Sign In"}
              </Link>
            </div>
          </motion.div>

          {/* Right — Overlap Graphics */}
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.7, delay: 0.15, ease: "easeOut" }}
            className="hero-right-graphics"
          >
            {/* Background Sheet Document */}
            <div className="animate-float hero-doc-sheet">
              <div className="doc-sheet-line-accent" />
              <div className="doc-sheet-text-line w-full" />
              <div className="doc-sheet-text-line w-5-6" />
              <div className="doc-sheet-text-line w-2-3" />
              <div className="margin-top-32">
                <div className="doc-sheet-text-line w-full margin-bottom-16" />
                <div className="doc-sheet-text-line w-full margin-bottom-16" />
                <div className="doc-sheet-text-line w-2-3" />
              </div>
            </div>

            {/* Overlap Synthesis Card */}
            <div className="animate-float hero-synthesis-card">
              <div className="synthesis-card-header">
                <div className="synthesis-icon-box">
                  <Sparkles size={20} className="icon-on-primary" />
                </div>
                <span className="serif-heading synthesis-card-title">
                  AI Explanations
                </span>
              </div>
              <ul className="synthesis-features-list">
                {[
                  "Step-by-step conceptual breakdowns",
                  "Core formulas, derivations & proofs",
                  "Multi-disciplinary courses covered",
                ].map((item, idx) => (
                  <li key={idx} className="synthesis-feature-item">
                    <span className="synthesis-bullet-dot" />
                    <span className="synthesis-text">
                      {item}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Section 2: Engineered for Academic Excellence ── */}
      <section className="hero-section-2">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="sec-2-copy-row"
        >
          <h2 className="text-display-small serif-heading sec-2-title">
            <span className="italic-serif font-weight-400">Engineered for</span><br />
            Academic Excellence
          </h2>
          <div className="sec-2-body-wrap">
            <p className="sec-2-body-text">
              A robust toolkit designed to streamline exam preparation through intelligent automation and community collaboration.
            </p>
          </div>
        </motion.div>

        {/* Feature Grid Columns */}
        <div className="grid grid-cols-1 md:grid-cols-12 sec-2-features-grid">
          {/* Card 1 */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="md:col-span-8 card-filled sec-2-card-1"
          >
            <div className="sec-2-card-1-icon-box">
              <GraduationCap size={24} className="icon-on-primary" />
            </div>
            <h3 className="serif-heading sec-2-card-title-lg">
              Crowdsourced Solutions
            </h3>
            <p className="sec-2-card-desc-lg">
              Leveraging premium models through community contribution. Access high-quality answers generated collectively for past exams.
            </p>
          </motion.div>

          {/* Card 2 */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="md:col-span-4 card-outlined sec-2-card-2"
          >
            <div className="sec-2-card-2-icon-box">
              <BookOpen size={20} className="icon-primary" />
            </div>
            <h3 className="serif-heading sec-2-card-title-sm">
              Massive Paper Library
            </h3>
            <p className="sec-2-card-desc-sm">
              Access an organized archive of previous year papers. Filter by course code, session, and year to find exactly what you need.
            </p>
          </motion.div>
        </div>

        {/* ── Section 3: Upload & Earn ── */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="hero-section-3"
        >
          <div className="sec-3-icon-box">
            <Coins size={28} className="icon-on-tertiary" />
          </div>
          <div className="sec-3-body-wrap">
            <h3 className="serif-heading sec-3-title">
              Upload & Earn
            </h3>
            <p className="sec-3-desc">
              Contribute missing papers to earn credits and unlock answers. Your contributions help build the repository and reward you with valuable access.
            </p>
          </div>
        </motion.div>
      </section>
    </div>
  );
}
